// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GeocachingAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BulkResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkResponse class.
        /// </summary>
        public BulkResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkResponse class.
        /// </summary>
        public BulkResponse(IList<string> successes = default(IList<string>), IList<BulkFailure> failures = default(IList<BulkFailure>))
        {
            Successes = successes;
            Failures = failures;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "successes")]
        public IList<string> Successes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failures")]
        public IList<BulkFailure> Failures { get; set; }

    }
}
