// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GeocachingAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GeocacheCount
    {
        /// <summary>
        /// Initializes a new instance of the GeocacheCount class.
        /// </summary>
        public GeocacheCount() { }

        /// <summary>
        /// Initializes a new instance of the GeocacheCount class.
        /// </summary>
        public GeocacheCount(GeocacheType geocacheType = default(GeocacheType), int? count = default(int?))
        {
            GeocacheType = geocacheType;
            Count = count;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "geocacheType")]
        public GeocacheType GeocacheType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
