// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GeocachingAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PostGeocacheList
    {
        /// <summary>
        /// Initializes a new instance of the PostGeocacheList class.
        /// </summary>
        public PostGeocacheList() { }

        /// <summary>
        /// Initializes a new instance of the PostGeocacheList class.
        /// </summary>
        public PostGeocacheList(string name, string description = default(string), int? typeId = default(int?), bool? isPublic = default(bool?), bool? isShared = default(bool?))
        {
            Name = name;
            Description = description;
            TypeId = typeId;
            IsPublic = isPublic;
            IsShared = isShared;
        }

        /// <summary>
        /// Name of the list
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Description of the list
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// List Type
        /// </summary>
        [JsonProperty(PropertyName = "typeId")]
        public int? TypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPublic")]
        public bool? IsPublic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isShared")]
        public bool? IsShared { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
