// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace GeocachingAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Sponsor
    {
        /// <summary>
        /// Initializes a new instance of the Sponsor class.
        /// </summary>
        public Sponsor() { }

        /// <summary>
        /// Initializes a new instance of the Sponsor class.
        /// </summary>
        public Sponsor(string name = default(string), string relatedWebPage = default(string), string relatedWebPageText = default(string))
        {
            Name = name;
            RelatedWebPage = relatedWebPage;
            RelatedWebPageText = relatedWebPageText;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relatedWebPage")]
        public string RelatedWebPage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relatedWebPageText")]
        public string RelatedWebPageText { get; set; }

    }
}
